---
title: "R Notebook"
output: html_notebook
---


```{r load packages}
library(dplyr)
library(tidyr)
library(zoo)
library(ggplot2)
library(ggpubr)
library(ggfortify)
library(data.table)
library(RColorBrewer)
library(vcd)
library(UpSetR)
library(MASS)
library(lm.beta)
library(reghelper)
```

```{r}
rosmap_path<-'C:/Users/yangmu/Desktop/rosmap/'
```

```{r load regression data, echo=TRUE, results="hide"}
phenotype_long<-read.csv(file.path(rosmap_path,'phenotype_long.csv'), header = TRUE)
phenotype_long$age_round <- round(phenotype_long$age_at_visit)

phenotype_basic <- read.csv(file.path(rosmap_path,'phenotype_basic.csv'), header = TRUE)
# setting variables for regression model
basic_measures <- phenotype_basic %>%
  dplyr::select(projid,msex,age_bl,age_death,educ,scaled_to,apoe_genotype,
                cogdx,ad_reagan) 
phenotype_long <- left_join(phenotype_long,basic_measures, by ='projid')
phenotype_long$alive <- ifelse(is.na(phenotype_long$age_death),1,0)
```

```{r pivot wide and check missingness, include=FALSE}
global_wide <- phenotype_long %>%
  dplyr::select(projid, fu_year, cogn_global) %>%
  pivot_wider(names_from = fu_year, values_from = cogn_global)
naniar::vis_miss(global_wide)
global_cesdsum <- phenotype_long %>%
  dplyr::select(projid, fu_year, cesdsum) %>%
  pivot_wider(names_from = fu_year, values_from = cesdsum)
naniar::vis_miss(global_cesdsum)
global_rdepres <- phenotype_long %>%
  dplyr::select(projid, fu_year, r_depres) %>%
  pivot_wider(names_from = fu_year, values_from = r_depres)
naniar::vis_miss(global_rdepres)
phenotype_long$r_depres <- ifelse(phenotype_long$r_depres>4,NA,phenotype_long$r_depres) 
```


```{r removal}
removal_visit<-phenotype_long[phenotype_long$projid %in% names(which(table(phenotype_long$projid) < 2)), ]
phenotype_long_2 <- phenotype_long %>%
  filter(!(projid %in% removal_visit$projid))
removal_visit<-phenotype_long[phenotype_long$projid %in% names(which(table(phenotype_long$projid) < 5)), ]
phenotype_long_5 <- phenotype_long %>%
  filter(!(projid %in% removal_visit$projid))
```

```{r, include=FALSE}
set.seed(970417)
library(lcmm)
#linear LCGA fixed model
#cogn_lcga1 <- hlme(cogn_global ~ fu_year+age_bl, subject = "projid", ng = 1, 
#              data =phenotype_long_2)
#cogn_lcga2 <- gridsearch(rep = 100, maxiter = 10, minit = cogn_lcga1, 
#                     hlme(cogn_global ~ fu_year+age_bl, subject = "projid", 
#                          ng = 2,data = phenotype_long_2, mixture = ~ fu_year, 
#                          nwg=T)) 
#cogn_lcga3 <- gridsearch(rep = 100, maxiter = 10, minit = cogn_lcga1,
#                     hlme(cogn_global ~ fu_year+age_bl, subject = "projid", 
#                          ng = 3, data = phenotype_long_2, mixture = ~ fu_year, 
#                          nwg=T))
#cogn_lcga4 <- gridsearch(rep = 100, maxiter = 10, minit = cogn_lcga1,
#                     hlme(cogn_global ~ fu_year+age_bl, subject = "projid", 
#                          ng = 4, data = phenotype_long_2, mixture = ~ fu_year, 
#                          nwg=T))
#summarytable(cogn_lcga1,cogn_lcga2,cogn_lcga3,cogn_lcga4)

#linear GMM random intercept
cogn_gmm1 <- hlme(cogn_global ~ fu_year+age_bl, subject = "projid", random=~1, ng = 1, 
                  data =phenotype_long_2)
cogn_gmm2 <- gridsearch(rep = 100, maxiter = 10, minit = cogn_gmm1, 
                     hlme(cogn_global ~ fu_year+age_bl, subject = "projid", 
                          random=~1,
                          ng = 2,data = phenotype_long_2, mixture = ~ fu_year, 
                          nwg=T)) 
cogn_gmm3 <- gridsearch(rep = 100, maxiter = 10, minit = cogn_gmm1,
                     hlme(cogn_global ~ fu_year+age_bl, subject = "projid", 
                          random=~1,
                          ng = 3, data = phenotype_long_2, mixture = ~ fu_year, 
                          nwg=T))
cogn_gmm4 <- gridsearch(rep = 100, maxiter = 10, minit = cogn_gmm1,
                     hlme(cogn_global ~ fu_year+age_bl, subject = "projid", 
                          random=~1,
                          ng = 4, data = phenotype_long_2, mixture = ~ fu_year, 
                          nwg=T))
#summarytable(cogn_gmm1,cogn_gmm2,cogn_gmm3,cogn_gmm4)

#linear GMM random intercept + random slope
cogn_gmm1_2 <- hlme(cogn_global ~ fu_year+age_bl, subject = "projid", random=~1 + fu_year, ng = 1,
                    data =phenotype_long_2)
cogn_gmm2_2 <- gridsearch(rep = 100, maxiter = 10, minit = cogn_gmm1_2, 
                     hlme(cogn_global ~ fu_year+age_bl, subject = "projid", 
                          random=~1 + fu_year,
                          ng = 2,data = phenotype_long_2, mixture = ~ fu_year, 
                          nwg=T)) 
cogn_gmm3_2 <- gridsearch(rep = 100, maxiter = 10, minit = cogn_gmm1_2,
                     hlme(cogn_global ~ fu_year+age_bl, subject = "projid", 
                          random=~1+fu_year,
                          ng = 3, data = phenotype_long_2, mixture = ~ fu_year, 
                          nwg=T))
cogn_gmm4_2 <- gridsearch(rep = 100, maxiter = 10, minit = cogn_gmm1_2,
                     hlme(cogn_global ~ fu_year+age_bl, subject = "projid", 
                          random=~1+fu_year,
                          ng = 4, data = phenotype_long_2, mixture = ~ fu_year, 
                          nwg=T))
#summarytable(cogn_gmm1_2,cogn_gmm2_2,cogn_gmm3_2,cogn_gmm4_2)
```

```{r save}
saveRDS(cogn_gmm1, file.path(rosmap_path,'cogn_gmm1.rds'))
saveRDS(cogn_gmm2, file.path(rosmap_path,'cogn_gmm2.rds'))
saveRDS(cogn_gmm3, file.path(rosmap_path,'cogn_gmm3.rds'))
saveRDS(cogn_gmm4, file.path(rosmap_path,'cogn_gmm4.rds'))
saveRDS(cogn_gmm1_2, file.path(rosmap_path,'cogn_gmm1_2.rds'))
saveRDS(cogn_gmm2_2, file.path(rosmap_path,'cogn_gmm2_2.rds'))
saveRDS(cogn_gmm3_2, file.path(rosmap_path,'cogn_gmm3_2.rds'))
saveRDS(cogn_gmm4_2, file.path(rosmap_path,'cogn_gmm4_2.rds'))
my_model <- readRDS(file.path(rosmap_path,'cogn_gmm4_2.rds'))
```


```{r plot on fu_year}
# + geom_line() + facet_grid(.~ __)
global_year <- ggplot(data = phenotype_long_2, aes(x = fu_year, y = cogn_global, group = projid))
r_depres_year <- ggplot(data = phenotype_long_2, aes(x = fu_year, y = r_depres, group = projid))
cesdsum_year <- ggplot(data = phenotype_long_2, aes(x = fu_year, y = cesdsum, group = projid))
```


